### ISSUE TITLE
Chinnerys Poster

### ISSUE THREAD

**Issue by TalliLlani** [TalliLlani/demo-project#4]
[TFAI_Chins.pdf](https://github.com/TalliLlani/demo-project/files/2214753/TFAI_Chins.pdf)

@mrlukemackenzie 

What do you think to this? - Any amends or details to add?

I can mock up an alternative with pics of you guys playing, wouldn't take long!

**Comment by mrlukemackenzie** [comment]
Can you do one with us playing and remove the price please? X

**Comment by TalliLlani** [comment]
![tfai_chins_2](https://user-images.githubusercontent.com/41257890/43022226-6f92aa4c-8c5e-11e8-9b1b-abe845278a60.png)
@mrlukemackenzie 
How about this?

How am I doing with the Git by the way? X

**Comment by mrlukemackenzie** [comment]
I've emailed you two more Sean pics to try. Can the plain black bit at the top be removed so the title is in the bubbles? Thank you. X

**Comment by TalliLlani** [comment]
@mrlukemackenzie  - Hows this? X

![tfai_chins_2 2](https://user-images.githubusercontent.com/41257890/43040721-01b9111a-8d43-11e8-93b7-6d9cbb542c5c.png)

**Comment by mrlukemackenzie** [comment]
Fucking awesome!  Any chance we can lose the tiny white line at the bottom
of tge Tug pic? X

**Comment by TalliLlani** [comment]
@mrlukemackenzie 

Last one! X
![tfai_chins_11 aug 18](https://user-images.githubusercontent.com/41257890/43049880-3f568606-8df7-11e8-9e4f-5754eb25f23a.png)
